services:
  coco-salvaje-integraciones:
    image: integraciones-client:staging
    container_name: integraciones-client-staging
    user: "1001:1001"
    ports:
      - "3001:3000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - coco-network

networks:
  coco-network:
    external: true